# Base Image
FROM biocontainers/biocontainers:latest


# Metadata
LABEL base.image="biocontainers:latest"
LABEL version="1"
LABEL software="RepeatMasker"
LABEL software.version="4.0.7"
LABEL description="Repeatmasking software utalzining a library base approach"
LABEL website="http://www.repeatmasker.org/"
LABEL documentation="https://www.animalgenome.org/bioinfo/resources/manuals/RepeatMasker.html"
LABEL license="https://opensource.org/licenses/osl-2.1.php"
LABEL tags="Genomics"



MAINTAINER John Pablo Mendieta <pablo.mendieta75@gmail.com>

RUN conda install repeatmasker


workdir /data/















